### ISSUE TITLE
global box-sizing border box breaks carousel

### ISSUE THREAD

**Issue by pdewouters** [jeremyfry/PikaChoose#12]
Hi,
first of all great work, so thanks!
I'm integrating the carousel on a website, where I had applied the following rule:
/\* apply a natural box layout model to all elements */
- { -moz-box-sizing: border-box; -webkit-box-sizing: border-box; box-sizing: border-box; }

it completely breaks the carousel, so I thought I'd let you know as this technique is becoming popular following Paul Irish blog post.

**Comment by jeremyfry** [comment]
The carousel is actually jCarousel developed by sorgalla. I'll check if he has a new version available that takes this into account.
