### ISSUE TITLE
Images Shift during transition

### ISSUE THREAD

**Issue by mihirc** [jeremyfry/PikaChoose#16]
Hello,

I am using PikaChoose to integrate it with a a Joomla Extension called as SOBIPro. The integration is working fine and i have no issues in running the code, except that when the transitions start, the images go on top of the pages before shifting down back to the current page.

Is it an issue with my code, or its an issue with PikaChoose.

Btw, why called Pika, why not Pichu :)

Regards,
Mihir.

**Comment by jeremyfry** [comment]
Figured calling it Pika and using a Pichu might dodge a lawsuit one day :D 

Sounds like the pika-stage element doesn't have a position applied to it. If you have a site url I can take a peak.

**Comment by rhettl** [comment]
I am having this issue as well. My page is behind a password that I don't have permission to give out.
I am not in any standard CMS or Framework. 
Best description I can give for any of the fading transitions is that from A, B appears, A re-appears and fades away.

My best guess is that the B image is on the wrong layer and should be closer to the background.

I did make a video and here is the youtube link: http://youtu.be/t_VmliFZ2vk

**Comment by jeremyfry** [comment]
Yeah something is not right there. I'm wondering if there is some z-indexes that have been shuffled around? Hard to say without being able to look at the code.

**Comment by rhettl** [comment]
Well, I am going to let down the password protection of the site for a day or so.
I would be most appreciative if you would take a look at the code in place.
it is right on the home page.

http://edc.ishowcasedatacenter.com

**Comment by rhettl** [comment]
Hello? Sorry, I don't mean to be pushy. I just need to go live with this website. I like PikaChoose and want to use it on the above site as I have with some of my previous sites but if I can't get this solved I have to change the slider. :-(
