### ISSUE TITLE
Namespace the events

### ISSUE THREAD

**Issue by ProLoser** [jeremyfry/PikaChoose#2]
Hello, just some feedback I thought I'd give since I've been reading some documentation on writing plugins in jquery. This problem may have been resolved by now, but in the past when I was working on a project with this plugin, I remember encountering an error where links inside the slideshow were being binded and unbinded (causing problems for a specific build of my code).

Today I came across this: http://ajpiano.com/widgetfactory/#slide12

I was thinking perhaps you may want to consider 'namespacing your events' for the slideshow so that you don't accidentally unbind events pertaining to other developers code (which has happened to me before). Hopefully this makes sense as I may be recalling the wrong plugin I was using at the time I was having problems.

**Comment by jeremyfry** [comment]
Interesting read. The way PikaChoose is coded accomplishes roughly the same thing. All variables and functions are stored in the jQuery.fn.pikachoose scope.

**Comment by ProLoser** [comment]
I was actually referring to the events. I noticed another plugins that you
can actually namespace events. the problem I experienced was when you
unbinded click events it would unbind other behaviors  I was trying to work
with that I had attached outside of the plugin.
On May 24, 2011 5:53 AM, "jeremyfry" <
reply@reply.github.com>
wrote:
