### ISSUE TITLE
Picachoose problem in Firefox

### ISSUE THREAD

**Issue by Elenabea** [jeremyfry/PikaChoose#6]
Please, help me to adjust this perfect script. Just one problem I have… When I refresh the page in Firefox browser, all slider images on 1 second drawn up in one column one above another.  Picachoose version 4.3.5. Somebody could help me to solve this problem, please? 

P.S. Please, sorry for my bad English.

**Comment by jeremyfry** [comment]
This is working as intended. If your user disables javascript the images will still be visible and clickable.
