### ISSUE TITLE
event.layerX and event.layerY are broken and deprecated in WebKit

### ISSUE THREAD

**Issue by vasia123** [jeremyfry/PikaChoose#8]
I received this warning in the console of Google Chrome using PikaChoose:

event.layerX and event.layerY are broken and deprecated in WebKit. They will be removed from the engine in the near future.

this worry?

**Comment by jeremyfry** [comment]
Nothing to worry about here. Just a jQuery issue. Nothing that will affect PikaChoose.

**Comment by avanturist888** [comment]
ok. thanks for reply.
