### ISSUE TITLE
Vertical Carousel is not applied when data is fed through an array using the data attribute.

### ISSUE THREAD

**Issue by funkjunky** [jeremyfry/PikaChoose#9]
$(#mydiv").PikaChoose({data: [{...},...], verticalCarousel: true})

The carousel shows up on the bottom, rather than the right/left.

**Comment by funkjunky** [comment]
I'll be looking more into this tomorrow morning. I love your code, so I don't think it will take long to find the 'cause and fix it.

Cheers.

**Comment by jeremyfry** [comment]
Shouldn't make a difference. Have a URL I can take a peek at?

**Comment by funkjunky** [comment]
Internal app, but I tried take your right example and using data instead of
the list and the same issue occurred.

EDIT: The attachement didn't work, haha. No prob. I'll upload it somewhere.

Cheers,

Jason

On Mon, Jan 30, 2012 at 3:39 PM, Jeremy Fry <
reply@reply.github.com

**Comment by funkjunky** [comment]
My company's filters block all manner of upload, so I put the htm file on pastebin.

http://pastebin.ca/2107882

**Comment by jeremyfry** [comment]
Looks like you have two issues causing the styling problems. 1, the div has an id of pikame which is picking up some of the ul styles. Try changing that id. 2, in the css change .jcarousel-skin-pika .jcarousel-clip-\* and remove the .jcarousel-skin-pika

**Comment by funkjunky** [comment]
I changed the id and of course that removed the centre, but it didn't change anything else that I noticed.
I don't know quite what you mean about the other css changes. I tried removing the ...-pika line, I tried removing ...-pike from the clip line, and replacing the "vertical" part with *, but that didn't work either.

I'll look into it some more right now.

**Comment by funkjunky** [comment]
I got the thumbnails to go vertical by setting the id to pikame in the plugin js.

**Comment by funkjunky** [comment]
Ya, it looks like the code is missing a div with the class skin-pika when the data attribute is used. I'll test it to be sure.

**Comment by funkjunky** [comment]
Got it! I simply added jcarousel-skin-pika as a class to the ul item.

Everything else in your code seems to do the same things it would when a ul is provided instead of data.

I like how you have it organized =).

So the changes are really small. Would you like me to specify the spots and what to change, or fork and merge or what?

**Comment by jeremyfry** [comment]
If you could make a fork and then shoot me a push request that would
be awesome.

Thank you,
Jeremy

Sent from my iPhone

On Jan 31, 2012, at 10:38 AM, funkjunky
reply@reply.github.com
wrote:
